name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"

permissions:
  contents: write

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Gera a animação da cobrinha
      - uses: Platane/snk@master
        with:
          github_user_name: GiseleNovaes
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Publica a animação na branch 'output'
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
